[package]
name = "gitfindr-rs"
version = "0.1.0"
authors = ["William Tarte <William.tarte6@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
directories = "3.0.1"